[package]
name = "gauntlet"
version = "0.1.0"
edition = "2021"

[dependencies]
applydiff-backend = { path = "../_backend" }
applydiff-core = { path = "../core" }
anyhow = "1.0"
tempfile = "3"
serde_json = "1.0"
md5 = "0.7.0"

# REMOVED: tauri is no longer needed as we call logic functions directly.