[workspace]
resolver = "2"
members = [
    "core",
    "_backend",
]

# Shared profiles for consistent behavior
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.dev]
panic = "abort"