[package]
name = "applydiff-core"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
thiserror = "1"
similar = "2"
strsim = "0.10"
chrono = { version = "0.4", features = ["clock", "std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
